name: Release Docker

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:

  release-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set TAG
        run: |
          if [[ -n "${{ inputs.tag }}" ]]; then
            TAG=${{ inputs.tag }}
          elif [[ "${{ github.ref_name }}" == 'main' ]]; then
            TAG="main"
          else
            TAG="${{ github.ref_name }}"
          fi
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Checkout Gitea
        uses: actions/checkout@v3
        with:
          repository: go-gitea/gitea
          ref: ${{ env.TAG }}
          fetch-depth: 1

      - name: Checkout Custom
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 1
          path: tk

      - name: Modify
        run: |
          \mv -f tk/actions.go modules/setting/actions.go

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push root docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}/gitea:${{ env.TAG }}
            ${{secrets.DOCKERHUB_USERNAME}}/gitea:latest

  release-docker-rootless:
    runs-on: ubuntu-latest
    steps:
      - name: Set TAG
        run: |
          if [[ -n "${{ inputs.tag }}" ]]; then
            TAG=${{ inputs.tag }}
          elif [[ "${{ github.ref_name }}" == 'main' ]]; then
            TAG="main"
          else
            TAG="${{ github.ref_name }}"
          fi
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Checkout Gitea
        uses: actions/checkout@v3
        with:
          repository: go-gitea/gitea
          ref: ${{ env.TAG }}
          fetch-depth: 1

      - name: Checkout Custom
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 1
          path: tk

      - name: Modify
        run: |
          \mv -f tk/actions.go modules/setting/actions.go

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push rootless docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.rootless
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/gitea:${{ env.TAG }}-rootless